######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 14 14:48:26 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Candle.h
SOURCES += Candle.cpp
