######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 15 15:48:53 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Candle.h Common.h CommonSystem.h CommonBot.h SystemSimulator.h TimePeriod.h
SOURCES += Candle.cpp Main.cpp SystemSimulator.cpp


QMAKE_CXXFLAGS_DEBUG += -pg -g3
QMAKE_LFLAGS_DEBUG += -pg -g3
